[package]
name = "apc"
version = "0.1.0"
authors = ["aftix <aftix@aftix.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip="0.5"
rusqlite="0.26"
json="0.12"
serde={version="1.0", features=["derive"]}
